name: fic_bloc2
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  http: ^1.0.0
  shared_preferences: ^2.1.1
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  google_fonts: ^5.0.0
  camera: ^0.10.5+2
  image_picker: ^0.8.9

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
